- name: Check if the namespace exists
  command: kubectl get namespace {{ harbor_namespace }} --ignore-not-found
  register: harbor_namespace_exists
  changed_when: false
  failed_when: false

- name: Create namespace if it does not exist
  k8s:
    api_version: v1
    kind: Namespace
    state: present
    name: "{{ harbor_namespace }}"
  when: harbor_namespace_exists.stdout == ""

- name: Create Harbor Certificate
  k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: harbor-tls
        namespace: "{{ harbor_namespace }}"
      spec:
        secretName: intranet-cert
        issuerRef:
          name: intranet
          kind: ClusterIssuer
        dnsNames:
          - "{{ harbor_domain }}"
