apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
  - name: cpu-stress
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "apk add --no-cache stress-ng && stress-ng --cpu 3 --cpu-load 80"]
    resources:
      limits:
        memory: "500Mi"
        cpu: "3"
      requests:
        memory: "200Mi"
        cpu: "3"
