apiVersion: v1
kind: Pod
metadata:
  name: ram-stress
spec:
  containers:
  - name: ram-stress
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "apk add --no-cache stress-ng && stress-ng --vm 1 --vm-bytes 1G"]
    resources:
      limits:
        memory: "2Gi"
        cpu: "300m"
      requests:
        memory: "1Gi"
        cpu: "200m"

