---
- name: Install grafana
  hosts: localhost
  vars_files:
    - ../vars/vars.yaml
    - ../vars/secret-vars.yaml

  roles:
   - deploy_kube_prometheus_stack
   - expose_kube_prometheus_stack_on_intranet
   - set_grafana_credentials
   - set_grafana_cluster_alerts
